/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useState } from "react";
import styled from "styled-components";

import { IconClock } from "@salutejs/plasma-icons";
import { Container } from "@salutejs/plasma-web/components/Grid";
import { TabItem, Tabs } from "@salutejs/plasma-web/components/Tabs";
import { DsplS, H2 } from "@salutejs/plasma-web/components/Typography";
import { Button } from "@/shared/ui";

const Wrapper = styled.div`
  padding: 20px;
  background-color: rgb(77, 43, 216);
`;

const ButtonWrapper = styled.div`
  display: flex;
  column-gap: 12px;
`;

const Divider = styled.div<{ size: string }>`
  height: ${({ size }) => `${size}px`};
`;

export default function Home() {
  const items = Array(8).fill("Tab");
  const [index, setIndex] = useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Wrapper>
          <DsplS bold={false} mt={24} mb={24} color="#fff">
            Можно&nbsp;ли открыть&nbsp;ИП на&nbsp;двоих человек в&nbsp;2024 году
          </DsplS>
          <ButtonWrapper>
            <Button view="primary">Читать</Button>
            <Button view="secondary">Поделиться</Button>
          </ButtonWrapper>
        </Wrapper>
        <Divider size="40" />
        <Container>
          <H2 color="#fff">Публикации</H2>
          <Divider size="24" />
          <Tabs view="filled" stretch size="xs">
            {items.map((tab, i) => (
              <TabItem
                view="secondary"
                key={`item:${i}`}
                size="s"
                selected={i === index}
                tabIndex={0}
                contentLeft={<IconClock size="xs" color="inherit" />}
                onClick={() => setIndex(i)}
                disabled={false}
              >
                {`${tab} ${i}`}
              </TabItem>
            ))}
          </Tabs>
          <Divider size="60" />
        </Container>
      </main>
    </>
  );
}
